"""Generate the 3-day ResearchAI capstone project (Days 96-98)."""
import json, os
BASE = "D:/AI ML SYLLABUS"

# ============================================================
# DAY 96: ResearchAI — Core RAG Pipeline
# ============================================================
day96 = os.path.join(BASE, "day 96 - research agent project")

# Main notebook
cells96 = [
    {"cell_type": "markdown", "metadata": {}, "source": [
        "# Day 96: ResearchAI — Building the Core RAG Pipeline\n",
        "## Day 1 of 3 — Document Ingestion, Embeddings & Retrieval\n\n",
        "**Goal Today:** Build the backbone of our AI Research Assistant — load documents, create embeddings, store in a vector DB, and answer questions.\n\n",
        "By Day 98, you'll have a complete AI agent that researches topics and generates reports with citations. This goes on your resume.\n\n",
        "---\n\n",
        "## Project Architecture\n\n",
        "```\n",
        "User Question\n",
        "    |\n",
        "    v\n",
        "[RAG Pipeline] -> Retrieve relevant docs\n",
        "    |\n",
        "    v\n",
        "[LangGraph Agent] -> Plan research, use tools\n",
        "    |\n",
        "    v\n",
        "[Multi-Agent Team]\n",
        "    ├── Researcher: Finds info from docs + web\n",
        "    ├── Writer: Synthesizes into a report\n",
        "    └── Reviewer: Checks quality, adds citations\n",
        "    |\n",
        "    v\n",
        "[Streamlit UI] -> User sees the final report\n",
        "```\n\n",
        "**Tech Stack:** Python, LangChain, ChromaDB, HuggingFace, Streamlit, LangGraph\n\n",
        "## Step 1: Project Setup"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Install dependencies (run once)\n",
        "# !pip install langchain langchain-community chromadb sentence-transformers pypdf streamlit\n",
        "\n",
        "import os\n",
        "import numpy as np\n",
        "from langchain.text_splitter import RecursiveCharacterTextSplitter\n",
        "from langchain.embeddings import HuggingFaceEmbeddings\n",
        "from langchain.vectorstores import Chroma\n",
        "from langchain.schema import Document\n",
        "from langchain.chains import RetrievalQA\n",
        "from langchain.prompts import PromptTemplate\n",
        "\n",
        "print('Libraries loaded! Core RAG pipeline ready to build.')"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 2: Create the Document Loader\n\n",
        "We'll build a document loader that can handle:\n",
        "- Plain text files\n",
        "- PDF files (using PyPDF)\n",
        "- Direct text input\n",
        "- Web page text"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "class DocumentLoader:\n",
        "    \"\"\"Load documents from various sources.\"\"\"\n",
        "    \n",
        "    @staticmethod\n",
        "    def from_text(text: str, source: str = \"manual\") -> list:\n",
        "        \"\"\"Create documents from raw text.\"\"\"\n",
        "        return [Document(page_content=text, metadata={\"source\": source})]\n",
        "    \n",
        "    @staticmethod\n",
        "    def from_file(filepath: str) -> list:\n",
        "        \"\"\"Load from .txt or .pdf file.\"\"\"\n",
        "        if filepath.endswith('.txt'):\n",
        "            with open(filepath, 'r', encoding='utf-8') as f:\n",
        "                text = f.read()\n",
        "            return [Document(page_content=text, metadata={\"source\": filepath})]\n",
        "        elif filepath.endswith('.pdf'):\n",
        "            from pypdf import PdfReader\n",
        "            reader = PdfReader(filepath)\n",
        "            docs = []\n",
        "            for i, page in enumerate(reader.pages):\n",
        "                text = page.extract_text()\n",
        "                if text:\n",
        "                    docs.append(Document(page_content=text, metadata={\"source\": filepath, \"page\": i+1}))\n",
        "            return docs\n",
        "        else:\n",
        "            raise ValueError(f\"Unsupported file type: {filepath}\")\n",
        "    \n",
        "    @staticmethod\n",
        "    def from_multiple(sources: list) -> list:\n",
        "        \"\"\"Load from multiple sources (files + text).\"\"\"\n",
        "        all_docs = []\n",
        "        for source in sources:\n",
        "            if isinstance(source, str) and os.path.exists(source):\n",
        "                all_docs.extend(DocumentLoader.from_file(source))\n",
        "            elif isinstance(source, str):\n",
        "                all_docs.extend(DocumentLoader.from_text(source))\n",
        "            elif isinstance(source, Document):\n",
        "                all_docs.append(source)\n",
        "        return all_docs\n",
        "\n",
        "print('DocumentLoader class created!')"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 3: Create Sample Research Documents\n\n",
        "For our research assistant, we'll create a knowledge base about AI/ML topics."
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Create sample research documents\n",
        "research_docs = [\n",
        "    Document(page_content=\"\"\"\n",
        "Artificial Intelligence in Healthcare: AI is transforming healthcare through improved diagnostics,\n",
        "drug discovery, and personalized medicine. Machine learning models can analyze medical images with\n",
        "accuracy rivaling human radiologists. Deep learning algorithms have detected breast cancer in\n",
        "mammograms with 94.5% accuracy. AI-powered systems can predict patient deterioration 6 hours\n",
        "before it happens. The global AI in healthcare market was valued at $15.4 billion in 2022 and\n",
        "is projected to reach $208.2 billion by 2030, growing at a CAGR of 38.4%.\n",
        "\"\"\", metadata={\"source\": \"healthcare_report_2024\", \"topic\": \"AI in Healthcare\"}),\n",
        "\n",
        "    Document(page_content=\"\"\"\n",
        "Machine Learning in Finance: Financial institutions use ML for fraud detection, algorithmic trading,\n",
        "credit scoring, and risk management. JP Morgan's COiN platform uses NLP to review 12,000 commercial\n",
        "loan agreements in seconds — work that previously took 360,000 hours annually. ML-based fraud\n",
        "detection systems save the banking industry approximately $12 billion annually. Robo-advisors\n",
        "managing over $1 trillion in assets use ML algorithms to optimize portfolio allocation.\n",
        "\"\"\", metadata={\"source\": \"finance_report_2024\", \"topic\": \"ML in Finance\"}),\n",
        "\n",
        "    Document(page_content=\"\"\"\n",
        "Natural Language Processing Advances: Transformer models like GPT-4, Claude, and Gemini have\n",
        "revolutionized NLP. These models can understand context, generate human-like text, translate\n",
        "languages, write code, and reason about complex topics. The key innovation is the attention\n",
        "mechanism that allows models to weigh the importance of different words in context. BERT,\n",
        "introduced in 2018, achieved state-of-the-art results on 11 NLP tasks. Modern LLMs are trained\n",
        "on trillions of tokens and can perform few-shot learning on unseen tasks.\n",
        "\"\"\", metadata={\"source\": \"nlp_report_2024\", \"topic\": \"NLP Advances\"}),\n",
        "\n",
        "    Document(page_content=\"\"\"\n",
        "Deep Learning for Computer Vision: CNNs have achieved superhuman performance on ImageNet\n",
        "classification. YOLO (You Only Look Once) can detect objects in real-time at 60 FPS.\n",
        "Vision Transformers (ViT) apply the transformer architecture to images, achieving state-of-the-art\n",
        "results. Generative models like DALL-E, Midjourney, and Stable Diffusion can create photorealistic\n",
        "images from text descriptions. Computer vision is used in autonomous vehicles, medical imaging,\n",
        "quality control in manufacturing, and augmented reality applications.\n",
        "\"\"\", metadata={\"source\": \"cv_report_2024\", \"topic\": \"Computer Vision\"}),\n",
        "\n",
        "    Document(page_content=\"\"\"\n",
        "The Future of Work with AI: According to McKinsey, AI could automate 60-70% of current work\n",
        "activities by 2030. However, AI is expected to create 97 million new jobs while displacing 85\n",
        "million. The key skills for the future include: AI/ML engineering, data science, prompt engineering,\n",
        "AI ethics and governance, and human-AI collaboration. Companies are investing heavily in\n",
        "reskilling programs. The World Economic Forum predicts that 50% of all employees will need\n",
        "reskilling by 2025 due to AI adoption.\n",
        "\"\"\", metadata={\"source\": \"future_work_2024\", \"topic\": \"Future of Work\"}),\n",
        "\n",
        "    Document(page_content=\"\"\"\n",
        "AI Ethics and Safety: Key concerns include bias in AI systems, privacy violations, job displacement,\n",
        "and the potential for misuse. The EU AI Act, passed in 2024, is the world's first comprehensive\n",
        "AI regulation, categorizing AI systems by risk level. Companies are establishing AI ethics boards\n",
        "and implementing responsible AI practices. Explainable AI (XAI) aims to make AI decisions\n",
        "transparent and interpretable. The field of AI alignment focuses on ensuring AI systems behave\n",
        "according to human values and intentions.\n",
        "\"\"\", metadata={\"source\": \"ethics_report_2024\", \"topic\": \"AI Ethics\"}),\n",
        "]\n",
        "\n",
        "print(f\"Created {len(research_docs)} research documents covering:\")\n",
        "for doc in research_docs:\n",
        "    print(f\"  - {doc.metadata['topic']} ({doc.metadata['source']})\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 4: Chunking & Embedding Pipeline"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "class RAGPipeline:\n",
        "    \"\"\"Complete RAG pipeline: chunk -> embed -> store -> retrieve.\"\"\"\n",
        "    \n",
        "    def __init__(self, chunk_size=500, chunk_overlap=50):\n",
        "        self.chunk_size = chunk_size\n",
        "        self.chunk_overlap = chunk_overlap\n",
        "        self.text_splitter = RecursiveCharacterTextSplitter(\n",
        "            chunk_size=chunk_size,\n",
        "            chunk_overlap=chunk_overlap,\n",
        "            separators=[\"\\n\\n\", \"\\n\", \". \", \" \", \"\"]\n",
        "        )\n",
        "        self.embeddings = HuggingFaceEmbeddings(\n",
        "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
        "        )\n",
        "        self.vectorstore = None\n",
        "        self.chunks = []\n",
        "    \n",
        "    def ingest(self, documents: list):\n",
        "        \"\"\"Ingest documents: split into chunks and store in vector DB.\"\"\"\n",
        "        self.chunks = self.text_splitter.split_documents(documents)\n",
        "        self.vectorstore = Chroma.from_documents(\n",
        "            documents=self.chunks,\n",
        "            embedding=self.embeddings,\n",
        "            persist_directory=\"./research_chroma_db\"\n",
        "        )\n",
        "        print(f\"Ingested {len(documents)} documents -> {len(self.chunks)} chunks\")\n",
        "        return self\n",
        "    \n",
        "    def retrieve(self, query: str, k: int = 3) -> list:\n",
        "        \"\"\"Retrieve most relevant chunks for a query.\"\"\"\n",
        "        if self.vectorstore is None:\n",
        "            raise ValueError(\"No documents ingested. Call .ingest() first.\")\n",
        "        retriever = self.vectorstore.as_retriever(search_kwargs={\"k\": k})\n",
        "        return retriever.invoke(query)\n",
        "    \n",
        "    def search(self, query: str, k: int = 3):\n",
        "        \"\"\"Search and display results nicely.\"\"\"\n",
        "        docs = self.retrieve(query, k)\n",
        "        print(f\"\\n{'='*60}\")\n",
        "        print(f\"Query: {query}\")\n",
        "        print('='*60)\n",
        "        for i, doc in enumerate(docs, 1):\n",
        "            print(f\"\\n[{i}] Source: {doc.metadata.get('source', 'unknown')}\")\n",
        "            print(f\"    Topic: {doc.metadata.get('topic', 'N/A')}\")\n",
        "            print(f\"    Content: {doc.page_content[:200]}...\")\n",
        "        return docs\n",
        "\n",
        "# Build the pipeline!\n",
        "rag = RAGPipeline()\n",
        "rag.ingest(research_docs)\n",
        "print(f\"\\nRAG Pipeline ready! {len(rag.chunks)} chunks in vector store.\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 5: Test the Retrieval"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Test queries\n",
        "test_queries = [\n",
        "    \"How is AI used in healthcare?\",\n",
        "    \"What is the impact of AI on jobs?\",\n",
        "    \"How do transformers work in NLP?\",\n",
        "    \"What are the ethical concerns with AI?\",\n",
        "]\n",
        "\n",
        "for query in test_queries:\n",
        "    rag.search(query, k=2)"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 6: Build the Research Report Generator\n\n",
        "Now we combine retrieval with a local LLM to generate research reports."
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "from transformers import pipeline\n",
        "\n",
        "class ResearchReportGenerator:\n",
        "    \"\"\"Generate research reports using RAG + LLM.\"\"\"\n",
        "    \n",
        "    def __init__(self, rag_pipeline):\n",
        "        self.rag = rag_pipeline\n",
        "        # Using a small local model (in production, use GPT-4/Claude API)\n",
        "        try:\n",
        "            self.generator = pipeline(\"text-generation\", model=\"gpt2\", max_length=300)\n",
        "        except:\n",
        "            self.generator = None\n",
        "            print(\"Note: GPT-2 not available. Using retrieval-only mode.\")\n",
        "            print(\"For best results, replace with OpenAI API in production.\")\n",
        "    \n",
        "    def generate_report(self, topic: str, num_sources: int = 3) -> str:\n",
        "        \"\"\"Generate a research report on a topic.\"\"\"\n",
        "        # Step 1: Retrieve relevant documents\n",
        "        relevant_docs = self.rag.retrieve(topic, k=num_sources)\n",
        "        \n",
        "        # Step 2: Build context from retrieved docs\n",
        "        context = \"\\n\\n\".join([\n",
        "            f\"[Source: {d.metadata.get('source', 'unknown')}]\\n{d.page_content}\"\n",
        "            for d in relevant_docs\n",
        "        ])\n",
        "        \n",
        "        # Step 3: Generate report\n",
        "        prompt = f\"\"\"You are a research assistant. Write a detailed research report on the following topic.\n",
        "Use the provided context to write an accurate, well-structured report with citations.\n",
        "\n",
        "TOPIC: {topic}\n",
        "\n",
        "CONTEXT:\n",
        "{context[:2000]}\n",
        "\n",
        "RESEARCH REPORT:\"\"\"\n",
        "        \n",
        "        if self.generator:\n",
        "            result = self.generator(prompt, max_length=400, temperature=0.3)[0]['generated_text']\n",
        "            # Remove the prompt from output\n",
        "            report = result.replace(prompt, '').strip()\n",
        "        else:\n",
        "            # Fallback: return structured summary of retrieved docs\n",
        "            report = self._generate_summary(topic, relevant_docs)\n",
        "        \n",
        "        return report\n",
        "    \n",
        "    def _generate_summary(self, topic: str, docs: list) -> str:\n",
        "        \"\"\"Generate a structured summary from retrieved docs (no LLM needed).\"\"\"\n",
        "        report = f\"# Research Report: {topic}\\n\\n\"\n",
        "        report += f\"*Generated from {len(docs)} sources*\\n\\n\"\n",
        "        \n",
        "        # Group by topic\n",
        "        topics = {}\n",
        "        for doc in docs:\n",
        "            t = doc.metadata.get('topic', 'General')\n",
        "            if t not in topics:\n",
        "                topics[t] = []\n",
        "            topics[t].append(doc)\n",
        "        \n",
        "        for topic_name, topic_docs in topics.items():\n",
        "            report += f\"## {topic_name}\\n\\n\"\n",
        "            for doc in topic_docs:\n",
        "                report += f\"{doc.page_content[:300]}...\\n\\n\"\n",
        "                report += f\"*Source: {doc.metadata.get('source', 'unknown')}*\\n\\n\"\n",
        "        \n",
        "        return report\n",
        "\n",
        "# Test the report generator\n",
        "reporter = ResearchReportGenerator(rag)\n",
        "report = reporter.generate_report(\"AI in healthcare and its future\")\n",
        "print(report[:600])\n",
        "print(\"\\n... (report continues)\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 7: Save the Pipeline for Tomorrow\n\n",
        "We'll save the RAG pipeline so Day 97 can load it directly."
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Save the document loader and RAG pipeline as a reusable module\n",
        "module_code = '''\n",
        "\"\"\"ResearchAI — Core RAG Pipeline Module.\"\"\"\n",
        "import os\n",
        "from langchain.text_splitter import RecursiveCharacterTextSplitter\n",
        "from langchain.embeddings import HuggingFaceEmbeddings\n",
        "from langchain.vectorstores import Chroma\n",
        "from langchain.schema import Document\n",
        "\n",
        "class DocumentLoader:\n",
        "    @staticmethod\n",
        "    def from_text(text, source=\"manual\"):\n",
        "        return [Document(page_content=text, metadata={\"source\": source})]\n",
        "    @staticmethod\n",
        "    def from_file(filepath):\n",
        "        if filepath.endswith('.txt'):\n",
        "            with open(filepath, 'r') as f:\n",
        "                return [Document(page_content=f.read(), metadata={\"source\": filepath})]\n",
        "        elif filepath.endswith('.pdf'):\n",
        "            from pypdf import PdfReader\n",
        "            reader = PdfReader(filepath)\n",
        "            return [Document(page_content=p.extract_text(), metadata={\"source\": filepath, \"page\": i+1}) for i, p in enumerate(reader.pages) if p.extract_text()]\n",
        "        raise ValueError(f\"Unsupported: {filepath}\")\n",
        "\n",
        "class RAGPipeline:\n",
        "    def __init__(self, chunk_size=500, chunk_overlap=50):\n",
        "        self.splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)\n",
        "        self.embeddings = HuggingFaceEmbeddings(model_name=\"sentence-transformers/all-MiniLM-L6-v2\")\n",
        "        self.vectorstore = None\n",
        "    def ingest(self, docs):\n",
        "        chunks = self.splitter.split_documents(docs)\n",
        "        self.vectorstore = Chroma.from_documents(chunks, self.embeddings, persist_directory=\"./research_db\")\n",
        "        return self\n",
        "    def retrieve(self, query, k=3):\n",
        "        return self.vectorstore.as_retriever(search_kwargs={\"k\": k}).invoke(query)\n",
        "'''\n",
        "\n",
        "os.makedirs('researchai', exist_ok=True)\n",
        "with open('researchai/__init__.py', 'w') as f:\n",
        "    f.write('from .pipeline import RAGPipeline, DocumentLoader')\n",
        "with open('researchai/pipeline.py', 'w') as f:\n",
        "    f.write(module_code)\n",
        "\n",
        "print(\"Module saved to researchai/pipeline.py\")\n",
        "print(\"\\n=== DAY 96 COMPLETE ===\")\n",
        "print(\"Built: DocumentLoader, RAGPipeline, ResearchReportGenerator\")\n",
        "print(\"Tomorrow: LangGraph Agent + Multi-Agent System\")"
    ]},
]

nb96 = {"cells": cells96, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}}, "nbformat": 4, "nbformat_minor": 4}
with open(os.path.join(day96, "Day96_ResearchAI_Core_Pipeline.ipynb"), "w", encoding="utf-8") as f:
    json.dump(nb96, f, indent=1, ensure_ascii=False)
print("Day 96 done!")


# ============================================================
# DAY 97: LangGraph Agent + Multi-Agent System
# ============================================================
day97 = os.path.join(BASE, "day 97 - research agent project")

cells97 = [
    {"cell_type": "markdown", "metadata": {}, "source": [
        "# Day 97: ResearchAI — Multi-Agent Research System\n",
        "## Day 2 of 3 — LangGraph Agents That Research, Write & Review\n\n",
        "**Goal Today:** Transform our RAG pipeline into a team of AI agents that collaborate to research any topic and produce a complete report.\n\n",
        "We'll build 3 agents:\n",
        "- **Researcher** — Finds and extracts relevant information\n",
        "- **Writer** — Synthesizes findings into a structured report\n",
        "- **Reviewer** — Checks quality, suggests improvements\n\n",
        "Orchestrated by **LangGraph** — the same framework from Days 71-80!"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Load Day 96's pipeline\n",
        "import sys, os\n",
        "sys.path.insert(0, '.')\n",
        "\n",
        "from researchai.pipeline import RAGPipeline, DocumentLoader\n",
        "from langchain.schema import Document\n",
        "import json\n",
        "\n",
        "# Recreate the knowledge base (or load from saved)\n",
        "research_docs = [\n",
        "    Document(page_content=\"AI in Healthcare: AI transforms healthcare through diagnostics, drug discovery, and personalized medicine. ML models analyze medical images with accuracy rivaling human radiologists. Global AI healthcare market: $15.4B (2022) to $208.2B by 2030.\", metadata={\"source\": \"healthcare\", \"topic\": \"AI in Healthcare\"}),\n",
        "    Document(page_content=\"ML in Finance: Financial institutions use ML for fraud detection, trading, and credit scoring. JP Morgan's COiN reviews 12,000 loan agreements in seconds. ML fraud detection saves $12B annually.\", metadata={\"source\": \"finance\", \"topic\": \"ML in Finance\"}),\n",
        "    Document(page_content=\"NLP Advances: GPT-4, Claude, and Gemini revolutionized NLP. Attention mechanism is the key innovation. BERT (2018) achieved SOTA on 11 NLP tasks. LLMs trained on trillions of tokens.\", metadata={\"source\": \"nlp\", \"topic\": \"NLP Advances\"}),\n",
        "    Document(page_content=\"Computer Vision: CNNs superhuman on ImageNet. YOLO detects objects at 60 FPS. Vision Transformers achieve SOTA. DALL-E and Stable Diffusion create photorealistic images from text.\", metadata={\"source\": \"cv\", \"topic\": \"Computer Vision\"}),\n",
        "    Document(page_content=\"Future of Work: AI could automate 60-70% of work by 2030 (McKinsey). AI to create 97M jobs while displacing 85M. 50% of employees need reskilling by 2025 (WEF).\", metadata={\"source\": \"future_work\", \"topic\": \"Future of Work\"}),\n",
        "    Document(page_content=\"AI Ethics: EU AI Act (2024) is first comprehensive AI regulation. Companies establishing ethics boards. XAI makes decisions transparent. AI alignment focuses on human values.\", metadata={\"source\": \"ethics\", \"topic\": \"AI Ethics\"}),\n",
        "]\n",
        "\n",
        "rag = RAGPipeline()\n",
        "rag.ingest(research_docs)\n",
        "print(\"RAG Pipeline loaded! Ready to build agents.\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 1: Build the Three Agents"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "class ResearcherAgent:\n",
        "    \"\"\"Searches for information on a given topic.\"\"\"\n",
        "    \n",
        "    def __init__(self, rag_pipeline):\n",
        "        self.rag = rag_pipeline\n",
        "        self.name = \"Researcher\"\n",
        "    \n",
        "    def research(self, topic: str, depth: int = 3) -> dict:\n",
        "        \"\"\"Research a topic and return findings.\"\"\"\n",
        "        print(f\"\\n[{self.name}] Researching: {topic}\")\n",
        "        \n",
        "        # Search for information\n",
        "        docs = self.rag.retrieve(topic, k=depth)\n",
        "        \n",
        "        # Extract key findings\n",
        "        findings = []\n",
        "        sources_used = set()\n",
        "        \n",
        "        for doc in docs:\n",
        "            source = doc.metadata.get('source', 'unknown')\n",
        "            topic_name = doc.metadata.get('topic', 'General')\n",
        "            \n",
        "            if source not in sources_used:\n",
        "                findings.append({\n",
        "                    'source': source,\n",
        "                    'topic': topic_name,\n",
        "                    'content': doc.page_content[:300],\n",
        "                    'relevance': 'high'\n",
        "                })\n",
        "                sources_used.add(source)\n",
        "        \n",
        "        print(f\"[{self.name}] Found {len(findings)} relevant sources\")\n",
        "        return {\n",
        "            'query': topic,\n",
        "            'findings': findings,\n",
        "            'num_sources': len(findings)\n",
        "        }\n",
        "\n",
        "class WriterAgent:\n",
        "    \"\"\"Synthesizes research findings into a structured report.\"\"\"\n",
        "    \n",
        "    def __init__(self):\n",
        "        self.name = \"Writer\"\n",
        "    \n",
        "    def write(self, research_data: dict, style: str = \"comprehensive\") -> str:\n",
        "        \"\"\"Write a report from research findings.\"\"\"\n",
        "        print(f\"\\n[{self.name}] Writing report...\")\n",
        "        \n",
        "        findings = research_data.get('findings', [])\n",
        "        query = research_data.get('query', 'Research Topic')\n",
        "        \n",
        "        # Build the report\n",
        "        report = f\"# Research Report: {query}\\n\\n\"\n",
        "        report += f\"*Generated by ResearchAI Multi-Agent System*\\n\"\n",
        "        report += f\"*Sources consulted: {len(findings)}*\\n\\n\"\n",
        "        report += \"---\\n\\n\"\n",
        "        \n",
        "        # Executive Summary\n",
        "        report += \"## Executive Summary\\n\\n\"\n",
        "        report += f\"This report examines {query} based on an analysis of {len(findings)} sources. \"\n",
        "        \n",
        "        topics_covered = set(f['topic'] for f in findings)\n",
        "        report += f\"The research covers: {', '.join(topics_covered)}.\\n\\n\"\n",
        "        \n",
        "        # Key Findings by Topic\n",
        "        report += \"## Key Findings\\n\\n\"\n",
        "        for i, finding in enumerate(findings, 1):\n",
        "            report += f\"### {i}. {finding['topic']}\\n\\n\"\n",
        "            report += f\"{finding['content']}\\n\\n\"\n",
        "            report += f\"*Source: {finding['source']}*\\n\\n\"\n",
        "        \n",
        "        # Conclusion\n",
        "        report += \"## Conclusion\\n\\n\"\n",
        "        report += f\"Based on the research conducted, {query} is a significant area with \"\n",
        "        report += f\"implications across multiple domains. The findings suggest continued \"\n",
        "        report += f\"growth and innovation in this field.\\n\\n\"\n",
        "        \n",
        "        # References\n",
        "        report += \"## References\\n\\n\"\n",
        "        for i, finding in enumerate(findings, 1):\n",
        "            report += f\"{i}. {finding['source']}\\n\"\n",
        "        \n",
        "        print(f\"[{self.name}] Report written ({len(report)} characters)\")\n",
        "        return report\n",
        "\n",
        "class ReviewerAgent:\n",
        "    \"\"\"Reviews reports for quality, completeness, and accuracy.\"\"\"\n",
        "    \n",
        "    def __init__(self):\n",
        "        self.name = \"Reviewer\"\n",
        "    \n",
        "    def review(self, report: str, research_data: dict) -> dict:\n",
        "        \"\"\"Review a report and provide feedback.\"\"\"\n",
        "        print(f\"\\n[{self.name}] Reviewing report...\")\n",
        "        \n",
        "        findings = research_data.get('findings', [])\n",
        "        \n",
        "        # Quality checks\n",
        "        checks = {\n",
        "            'has_title': report.startswith('# '),\n",
        "            'has_sections': '## ' in report,\n",
        "            'has_sources': 'Source:' in report and len(findings) > 0,\n",
        "            'has_conclusion': 'Conclusion' in report,\n",
        "            'has_references': 'References' in report,\n",
        "            'min_length': len(report) > 500,\n",
        "        }\n",
        "        \n",
        "        passed = sum(1 for v in checks.values() if v)\n",
        "        total = len(checks)\n",
        "        score = (passed / total) * 10\n",
        "        \n",
        "        issues = []\n",
        "        if not checks['has_sources']:\n",
        "            issues.append(\"Missing source citations\")\n",
        "        if not checks['min_length']:\n",
        "            issues.append(\"Report too short\")\n",
        "        if not checks['has_conclusion']:\n",
        "            issues.append(\"Missing conclusion section\")\n",
        "        \n",
        "        result = {\n",
        "            'score': round(score, 1),\n",
        "            'passed': passed,\n",
        "            'total': total,\n",
        "            'checks': checks,\n",
        "            'issues': issues,\n",
        "            'approved': score >= 6.0\n",
        "        }\n",
        "        \n",
        "        print(f\"[{self.name}] Score: {score}/10 | {'APPROVED' if result['approved'] else 'NEEDS REVISION'}\")\n",
        "        if issues:\n",
        "            for issue in issues:\n",
        "                print(f\"  - Issue: {issue}\")\n",
        "        \n",
        "        return result\n",
        "\n",
        "print(\"Three agents defined: Researcher, Writer, Reviewer\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 2: Orchestrate with LangGraph"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Build the LangGraph workflow\n",
        "try:\n",
        "    from langgraph.graph import StateGraph, END\n",
        "    from typing import TypedDict, Annotated\n",
        "    import operator\n",
        "    \n",
        "    class ResearchState(TypedDict):\n",
        "        query: str\n",
        "        research_data: dict\n",
        "        report: str\n",
        "        review: dict\n",
        "        final_report: str\n",
        "    \n",
        "    def research_node(state: ResearchState) -> ResearchState:\n",
        "        researcher = ResearcherAgent(rag)\n",
        "        state['research_data'] = researcher.research(state['query'])\n",
        "        return state\n",
        "    \n",
        "    def write_node(state: ResearchState) -> ResearchState:\n",
        "        writer = WriterAgent()\n",
        "        state['report'] = writer.write(state['research_data'])\n",
        "        return state\n",
        "    \n",
        "    def review_node(state: ResearchState) -> ResearchState:\n",
        "        reviewer = ReviewerAgent()\n",
        "        state['review'] = reviewer.review(state['report'], state['research_data'])\n",
        "        state['final_report'] = state['report']\n",
        "        return state\n",
        "    \n",
        "    # Build graph\n",
        "    workflow = StateGraph(ResearchState)\n",
        "    workflow.add_node(\"research\", research_node)\n",
        "    workflow.add_node(\"write\", write_node)\n",
        "    workflow.add_node(\"review\", review_node)\n",
        "    workflow.set_entry_point(\"research\")\n",
        "    workflow.add_edge(\"research\", \"write\")\n",
        "    workflow.add_edge(\"write\", \"review\")\n",
        "    workflow.add_edge(\"review\", END)\n",
        "    \n",
        "    research_graph = workflow.compile()\n",
        "    print(\"LangGraph workflow built: Research -> Write -> Review\")\n",
        "    USING_LANGGRAPH = True\n",
        "except ImportError:\n",
        "    print(\"LangGraph not installed. Using manual orchestration.\")\n",
        "    USING_LANGGRAPH = False"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 3: The Complete Research System"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "class ResearchAI:\n",
        "    \"\"\"Complete Multi-Agent Research System.\"\"\"\n",
        "    \n",
        "    def __init__(self, rag_pipeline):\n",
        "        self.researcher = ResearcherAgent(rag_pipeline)\n",
        "        self.writer = WriterAgent()\n",
        "        self.reviewer = ReviewerAgent()\n",
        "        self.history = []\n",
        "    \n",
        "    def research_topic(self, query: str) -> dict:\n",
        "        \"\"\"Run the full research pipeline.\"\"\"\n",
        "        print(f\"\\n{'='*60}\")\n",
        "        print(f\"RESEARCH TOPIC: {query}\")\n",
        "        print('='*60)\n",
        "        \n",
        "        # Phase 1: Research\n",
        "        research_data = self.researcher.research(query)\n",
        "        \n",
        "        # Phase 2: Write\n",
        "        report = self.writer.write(research_data)\n",
        "        \n",
        "        # Phase 3: Review\n",
        "        review = self.reviewer.review(report, research_data)\n",
        "        \n",
        "        # Phase 4: Finalize\n",
        "        if review['approved']:\n",
        "            final_report = report\n",
        "            print(f\"\\n{'='*60}\")\n",
        "            print(\"REPORT APPROVED!\")\n",
        "            print('='*60)\n",
        "        else:\n",
        "            print(f\"\\nReport needs revision. Issues: {review['issues']}\")\n",
        "            final_report = report\n",
        "        \n",
        "        result = {\n",
        "            'query': query,\n",
        "            'research': research_data,\n",
        "            'report': final_report,\n",
        "            'review': review,\n",
        "        }\n",
        "        \n",
        "        self.history.append(result)\n",
        "        return result\n",
        "    \n",
        "    def get_report(self, query: str) -> str:\n",
        "        \"\"\"Research and return just the report.\"\"\"\n",
        "        result = self.research_topic(query)\n",
        "        return result['report']\n",
        "\n",
        "# Create the full system\n",
        "ai = ResearchAI(rag)\n",
        "print(\"\\nResearchAI system ready!\")\n",
        "print(\"Agents: Researcher -> Writer -> Reviewer\")\n",
        "print(\"\\nTry: ai.research_topic('Impact of AI on jobs')\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 4: Test the System!"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Test 1: Simple research query\n",
        "result1 = ai.research_topic(\"AI in healthcare\")\n",
        "print(\"\\n\" + result1['report'][:500])\n",
        "print(\"\\n... (full report generated)\")"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Test 2: Broader topic\n",
        "result2 = ai.research_topic(\"Future of AI and jobs\")\n",
        "print(\"\\n\" + result2['report'][:500])"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Show research history\n",
        "print(f\"\\nResearch history: {len(ai.history)} queries processed\")\n",
        "for i, entry in enumerate(ai.history, 1):\n",
        "    print(f\"  {i}. '{entry['query']}' — Score: {entry['review']['score']}/10\")\n",
        "    print(f\"     Sources: {entry['research']['num_sources']}, Approved: {entry['review']['approved']}\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 5: Save the Complete System"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Save all agent code as a module\n",
        "agent_code = '''\n",
        "\"\"\"ResearchAI — Multi-Agent Research System.\"\"\"\n",
        "import json\n",
        "\n",
        "class ResearcherAgent:\n",
        "    def __init__(self, rag): self.rag = rag; self.name = \"Researcher\"\n",
        "    def research(self, topic, depth=3):\n",
        "        docs = self.rag.retrieve(topic, k=depth)\n",
        "        findings = [{'source': d.metadata.get('source',''), 'topic': d.metadata.get('topic',''), 'content': d.page_content[:300]} for d in docs]\n",
        "        return {'query': topic, 'findings': findings, 'num_sources': len(findings)}\n",
        "\n",
        "class WriterAgent:\n",
        "    def __init__(self): self.name = \"Writer\"\n",
        "    def write(self, data, style=\"comprehensive\"):\n",
        "        findings = data.get('findings', []); query = data.get('query', '')\n",
        "        report = f\"# Research Report: {query}\\\\n\\\\n*Generated by ResearchAI*\\\\n*Sources: {len(findings)}*\\\\n\\\\n---\\\\n\\\\n## Executive Summary\\\\n\\\\nThis report examines {query} based on {len(findings)} sources.\\\\n\\\\n## Key Findings\\\\n\\\\n\"\n",
        "        for i, f in enumerate(findings, 1): report += f\"### {i}. {f['topic']}\\\\n\\\\n{f['content']}\\\\n\\\\n*Source: {f['source']}*\\\\n\\\\n\"\n",
        "        report += f\"## Conclusion\\\\n\\\\nBased on the research, {query} shows significant developments across multiple domains.\\\\n\\\\n## References\\\\n\\\\n\"\n",
        "        for i, f in enumerate(findings, 1): report += f\"{i}. {f['source']}\\\\n\"\n",
        "        return report\n",
        "\n",
        "class ReviewerAgent:\n",
        "    def __init__(self): self.name = \"Reviewer\"\n",
        "    def review(self, report, data):\n",
        "        checks = {'has_title': report.startswith('#'), 'has_sections': '##' in report, 'has_sources': 'Source:' in report, 'has_conclusion': 'Conclusion' in report, 'min_length': len(report) > 300}\n",
        "        passed = sum(1 for v in checks.values() if v); score = (passed/len(checks))*10\n",
        "        return {'score': round(score,1), 'passed': passed, 'total': len(checks), 'checks': checks, 'approved': score >= 5.0, 'issues': [k for k,v in checks.items() if not v]}\n",
        "\n",
        "class ResearchAI:\n",
        "    def __init__(self, rag):\n",
        "        self.researcher = ResearcherAgent(rag); self.writer = WriterAgent(); self.reviewer = ReviewerAgent(); self.history = []\n",
        "    def research_topic(self, query):\n",
        "        data = self.researcher.research(query); report = self.writer.write(data); review = self.reviewer.review(report, data)\n",
        "        result = {'query': query, 'research': data, 'report': report, 'review': review}\n",
        "        self.history.append(result); return result\n",
        "    def get_report(self, query): return self.research_topic(query)['report']\n",
        "'''\n",
        "\n",
        "with open('researchai/agents.py', 'w') as f:\n",
        "    f.write(agent_code)\n",
        "\n",
        "print(\"Agent module saved to researchai/agents.py\")\n",
        "print(\"\\n=== DAY 97 COMPLETE ===\")\n",
        "print(\"Built: ResearcherAgent, WriterAgent, ReviewerAgent, ResearchAI\")\n",
        "print(\"Tomorrow: Streamlit UI + Deploy!\")"
    ]},
]

nb97 = {"cells": cells97, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}}, "nbformat": 4, "nbformat_minor": 4}
with open(os.path.join(day97, "Day97_ResearchAI_Multi_Agent.ipynb"), "w", encoding="utf-8") as f:
    json.dump(nb97, f, indent=1, ensure_ascii=False)
print("Day 97 done!")


# ============================================================
# DAY 98: Streamlit UI + Deploy + Portfolio
# ============================================================
day98 = os.path.join(BASE, "day 98 - research agent project")

cells98 = [
    {"cell_type": "markdown", "metadata": {}, "source": [
        "# Day 98: ResearchAI — UI, Deploy & Portfolio\n",
        "## Day 3 of 3 — Ship It and Put It on Your Resume\n\n",
        "**Goal Today:** Build a beautiful Streamlit interface, deploy it live, write a great README, and make your project portfolio-ready.\n\n",
        "---\n\n",
        "## Step 1: Project Structure\n\n",
        "```\n",
        "ResearchAI/\n",
        "    researchai/\n",
        "        __init__.py\n",
        "        pipeline.py    # Day 96 — RAG pipeline\n",
        "        agents.py      # Day 97 — Multi-agent system\n",
        "    app.py             # Streamlit UI\n",
        "    requirements.txt   # Dependencies\n",
        "    README.md          # Portfolio documentation\n",
        "    .env.example       # API key template\n",
        "    .gitignore\n",
        "```"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 2: The Streamlit App"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Create the main Streamlit application\n",
        "app_code = '''\n",
        "\"\"\"ResearchAI — Multi-Agent Research Assistant.\"\"\"\n",
        "import streamlit as st\n",
        "import sys, os\n",
        "sys.path.insert(0, os.path.dirname(__file__))\n",
        "\n",
        "from researchai.pipeline import RAGPipeline, DocumentLoader\n",
        "from researchai.agents import ResearchAI\n",
        "from langchain.schema import Document\n",
        "\n",
        "# Page config\n",
        "st.set_page_config(page_title=\"ResearchAI\", page_icon=\"🔬\", layout=\"wide\")\n",
        "\n",
        "# Initialize session state\n",
        "if 'rag' not in st.session_state:\n",
        "    with st.spinner('Loading AI models...'):\n",
        "        # Load sample knowledge base\n",
        "        kb = [\n",
        "            Document(page_content=\"AI in Healthcare: AI transforms diagnostics, drug discovery, personalized medicine. Global market: $15.4B (2022) to $208.2B (2030), CAGR 38.4%.\", metadata={\"source\": \"healthcare_2024\", \"topic\": \"AI Healthcare\"}),\n",
        "            Document(page_content=\"ML in Finance: Fraud detection saves $12B/year. JP Morgan COiN processes 12K loans in seconds. Robo-advisors manage $1T+ assets.\", metadata={\"source\": \"finance_2024\", \"topic\": \"ML Finance\"}),\n",
        "            Document(page_content=\"NLP & Transformers: GPT-4, Claude, Gemini use attention mechanisms. BERT (2018) SOTA on 11 NLP tasks. LLMs trained on trillions of tokens.\", metadata={\"source\": \"nlp_2024\", \"topic\": \"NLP Advances\"}),\n",
        "            Document(page_content=\"Computer Vision: CNNs superhuman on ImageNet. YOLO real-time detection. Vision Transformers achieve SOTA. DALL-E creates images from text.\", metadata={\"source\": \"cv_2024\", \"topic\": \"Computer Vision\"}),\n",
        "            Document(page_content=\"Future of Work: AI may automate 60-70% of work by 2030 (McKinsey). Creates 97M jobs, displaces 85M. 50% need reskilling by 2025 (WEF).\", metadata={\"source\": \"work_2024\", \"topic\": \"Future of Work\"}),\n",
        "            Document(page_content=\"AI Ethics: EU AI Act (2024) first comprehensive regulation. XAI makes decisions transparent. AI alignment ensures human-compatible values.\", metadata={\"source\": \"ethics_2024\", \"topic\": \"AI Ethics\"}),\n",
        "        ]\n",
        "        st.session_state.rag = RAGPipeline().ingest(kb)\n",
        "        st.session_state.ai = ResearchAI(st.session_state.rag)\n",
        "        st.session_state.history = []\n",
        "\n",
        "# UI\n",
        "st.title(\"🔬 ResearchAI\")\n",
        "st.caption(\"Multi-Agent AI Research Assistant — Researcher + Writer + Reviewer\")\n",
        "\n",
        "# Sidebar\n",
        "with st.sidebar:\n",
        "    st.header(\"About\")\n",
        "    st.write(\"ResearchAI uses a team of AI agents to research any topic and generate detailed reports with citations.\")\n",
        "    st.divider()\n",
        "    st.subheader(\"Agent Team\")\n",
        "    st.write(\"🔍 **Researcher** — Finds relevant information\")\n",
        "    st.write(\"✍️ **Writer** — Creates structured reports\")\n",
        "    st.write(\"✅ **Reviewer** — Checks quality & accuracy\")\n",
        "    st.divider()\n",
        "    st.subheader(\"Research History\")\n",
        "    for i, entry in enumerate(st.session_state.history[-5:]):\n",
        "        with st.expander(f\"{i+1}. {entry['query'][:40]}...\", expanded=False):\n",
        "            st.write(f\"Score: {entry['review']['score']}/10\")\n",
        "            st.write(f\"Sources: {entry['research']['num_sources']}\")\n",
        "\n",
        "# Main area\n",
        "col1, col2 = st.columns([3, 1])\n",
        "with col1:\n",
        "    query = st.text_input(\"Research Topic:\", placeholder=\"e.g., Impact of AI on healthcare\")\n",
        "with col2:\n",
        "    st.write(\"\")  # spacer\n",
        "    search = st.button(\"🔍 Research\", type=\"primary\", use_container_width=True)\n",
        "\n",
        "if search and query:\n",
        "    with st.spinner(f'Researching: {query}...'):\n",
        "        result = st.session_state.ai.research_topic(query)\n",
        "        st.session_state.history.append(result)\n",
        "    \n",
        "    st.success(f\"Research complete! Score: {result['review']['score']}/10\")\n",
        "    \n",
        "    # Display report\n",
        "    st.markdown(result['report'])\n",
        "    \n",
        "    # Download button\n",
        "    st.download_button(\n",
        "        label=\"📥 Download Report\",\n",
        "        data=result['report'],\n",
        "        file_name=f\"research_report_{query[:30].replace(' ', '_')}.md\",\n",
        "        mime=\"text/markdown\"\n",
        "    )\n",
        "\n",
        "elif not query:\n",
        "    st.info(\"👆 Enter a research topic above and click Research to start!\")\n",
        "    st.markdown(\"\"\"\n",
        "    ### Example Topics:\n",
        "    - Impact of AI on healthcare\n",
        "    - Future of work and automation\n",
        "    - Machine learning in finance\n",
        "    - Ethics and regulation of AI\n",
        "    - Advances in natural language processing\n",
        "    \"\"\")\n",
        "'''\n",
        "\n",
        "os.makedirs('ResearchAI', exist_ok=True)\n",
        "with open('ResearchAI/app.py', 'w') as f:\n",
        "    f.write(app_code)\n",
        "print(\"Streamlit app created: ResearchAI/app.py\")\n",
        "print(\"\\nRun with: cd ResearchAI && streamlit run app.py\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 3: requirements.txt"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "requirements = \"\"\"streamlit>=1.28.0\n",
        "langchain>=0.1.0\n",
        "langchain-community>=0.1.0\n",
        "chromadb>=0.4.0\n",
        "sentence-transformers>=2.2.0\n",
        "pypdf>=3.0.0\n",
        "langgraph>=0.0.20\n",
        "\"\"\"\n",
        "\n",
        "with open('ResearchAI/requirements.txt', 'w') as f:\n",
        "    f.write(requirements)\n",
        "print(\"requirements.txt created\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 4: README.md — Your Portfolio Piece"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "readme = \"\"\"# 🔬 ResearchAI — Multi-Agent Research Assistant\n",
        "\n",
        "![Python](https://img.shields.io/badge/Python-3.10+-blue)\n",
        "![LangChain](https://img.shields.io/badge/LangChain-0.1+-green)\n",
        "![ChromaDB](https://img.shields.io/badge/ChromaDB-0.4+-orange)\n",
        "![Streamlit](https://img.shields.io/badge/Streamlit-1.28+-red)\n",
        "![License](https://img.shields.io/badge/License-MIT-yellow)\n",
        "\n",
        "An AI-powered research assistant that uses a **team of AI agents** to research any topic and generate comprehensive reports with citations.\n",
        "\n",
        "## Architecture\n",
        "\n",
        "```\n",
        "User Query → [RAG Pipeline] → [Multi-Agent System] → Research Report\n",
        "                  │                    │\n",
        "            ChromaDB Vector DB    ┌───┴───┐\n",
        "            + HuggingFace E5      │       │\n",
        "                              Researcher  Writer\n",
        "                                  │       │\n",
        "                              └───┬───┘\n",
        "                                 Reviewer\n",
        "```\n",
        "\n",
        "## Features\n",
        "\n",
        "- 🔍 **Semantic Search** — Finds relevant information from document knowledge base\n",
        "- 🤖 **3 AI Agents** — Researcher finds info, Writer creates reports, Reviewer checks quality\n",
        "- 📊 **Structured Reports** — Executive summary, key findings, conclusion, references\n",
        "- 💾 **Research History** — Saves all past queries and reports\n",
        "- 🎨 **Clean UI** — Built with Streamlit, mobile-responsive\n",
        "- 📥 **Export** — Download reports as Markdown\n",
        "\n",
        "## Quick Start\n",
        "\n",
        "```bash\n",
        "git clone https://github.com/YOUR_USERNAME/ResearchAI.git\n",
        "cd ResearchAI\n",
        "pip install -r requirements.txt\n",
        "streamlit run app.py\n",
        "```\n",
        "\n",
        "## Tech Stack\n",
        "\n",
        "| Component | Technology |\n",
        "|-----------|-----------|\n",
        "| RAG Pipeline | LangChain + ChromaDB |\n",
        "| Embeddings | HuggingFace (all-MiniLM-L6-v2) |\n",
        "| Agent Framework | LangGraph |\n",
        "| Frontend | Streamlit |\n",
        "| Language | Python 3.10+ |\n",
        "\n",
        "## How It Works\n",
        "\n",
        "1. **Document Ingestion** — Load PDFs, text files, or direct input\n",
        "2. **Chunking & Embedding** — Split into searchable chunks, create vector embeddings\n",
        "3. **Semantic Retrieval** — Find most relevant documents for a query\n",
        "4. **Multi-Agent Processing:**\n",
        "   - **Researcher Agent** gathers and extracts key information\n",
        "   - **Writer Agent** synthesizes into a structured report\n",
        "   - **Reviewer Agent** checks quality, completeness, and accuracy\n",
        "5. **Report Generation** — Final report with executive summary, findings, and citations\n",
        "\n",
        "## Project Structure\n",
        "\n",
        "```\n",
        "ResearchAI/\n",
        "├── researchai/\n",
        "│   ├── __init__.py\n",
        "│   ├── pipeline.py    # RAG: document loading, chunking, embedding, retrieval\n",
        "│   └── agents.py      # Multi-agent: Researcher, Writer, Reviewer\n",
        "├── app.py             # Streamlit web interface\n",
        "├── requirements.txt   # Python dependencies\n",
        "└── README.md\n",
        "```\n",
        "\n",
        "## Skills Demonstrated\n",
        "\n",
        "- ✅ Python OOP (classes, modular architecture)\n",
        "- ✅ RAG (Retrieval Augmented Generation)\n",
        "- ✅ Vector Databases (ChromaDB)\n",
        "- ✅ Multi-Agent AI Systems\n",
        "- ✅ LangChain & LangGraph\n",
        "- ✅ Streamlit Web Development\n",
        "- ✅ Embeddings & Semantic Search\n",
        "- ✅ Project Architecture & Documentation\n",
        "\n",
        "## Future Enhancements\n",
        "\n",
        "- [ ] Add web search tool (Tavily/SerpAPI)\n",
        "- [ ] Use GPT-4/Claude for better report generation\n",
        "- [ ] Add more agent roles (FactChecker, Summarizer)\n",
        "- [ ] Support more file types (DOCX, HTML, web URLs)\n",
        "- [ ] Deploy on Streamlit Cloud / HuggingFace Spaces\n",
        "- [ ] Add user authentication\n",
        "\n",
        "## License\n",
        "\n",
        "MIT — feel free to use, modify, and share!\n",
        "\"\"\"\n",
        "\n",
        "with open('ResearchAI/README.md', 'w') as f:\n",
        "    f.write(readme)\n",
        "print(\"README.md created — your portfolio documentation!\")"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 5: .gitignore + .env.example"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# .gitignore\n",
        "with open('ResearchAI/.gitignore', 'w') as f:\n",
        "    f.write(\"\"\"# Python\n",
        "__pycache__/\n",
        "*.pyc\n",
        ".env\n",
        "venv/\n",
        ".venv/\n",
        "\n",
        "# ChromaDB\n",
        "research_db/\n",
        "chroma_db/\n",
        "\n",
        "# Streamlit\n",
        ".streamlit/secrets.toml\n",
        "\"\"\")\n",
        "\n",
        "# .env.example\n",
        "with open('ResearchAI/.env.example', 'w') as f:\n",
        "    f.write(\"\"\"# API Keys (for production)\n",
        "# OPENAI_API_KEY=sk-...\n",
        "# TAVILY_API_KEY=tvly-...\n",
        "\"\"\")\n",
        "\n",
        "print(\"Project files created!\")\n",
        "print(\"\\nResearchAI/\")\n",
        "for root, dirs, files in os.walk('ResearchAI'):\n",
        "    level = root.replace('ResearchAI', '').count(os.sep)\n",
        "    indent = '  ' * level\n",
        "    print(f'{indent}{os.path.basename(root)}/')\n",
        "    subindent = '  ' * (level + 1)\n",
        "    for file in files:\n",
        "        print(f'{subindent}{file}')"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 6: How to Deploy\n\n",
        "### Option A: Streamlit Cloud (Easiest — FREE)\n",
        "```bash\n",
        "# 1. Push to GitHub\n",
        "git init\n",
        "git add .\n",
        "git commit -m 'ResearchAI v1.0'\n",
        "git push origin main\n",
        "\n",
        "# 2. Go to https://share.streamlit.io\n",
        "# 3. Click 'New app' -> Select your repo -> Deploy!\n",
        "```\n\n",
        "### Option B: HuggingFace Spaces (FREE)\n",
        "```bash\n",
        "# 1. Create a new Space at https://huggingface.co/spaces\n",
        "# 2. Choose Streamlit SDK\n",
        "# 3. Upload your files or connect GitHub\n",
        "```\n\n",
        "### Option C: Run Locally\n",
        "```bash\n",
        "cd ResearchAI\n",
        "pip install -r requirements.txt\n",
        "streamlit run app.py\n",
        "# Opens at http://localhost:8501\n",
        "```"
    ]},
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Step 7: Your Resume Bullet Points\n\n",
        "Copy these to your resume:\n\n",
        "```\n",
        "🔬 ResearchAI — Multi-Agent AI Research Assistant\n",
        "- Built an AI system using LangChain, ChromaDB, and LangGraph that researches\n",
        "  any topic using a team of 3 AI agents (Researcher, Writer, Reviewer)\n",
        "- Implemented RAG (Retrieval Augmented Generation) with semantic search\n",
        "  for document retrieval from a vector database\n",
        "- Created a Streamlit web interface for real-time research with report export\n",
        "- Tech: Python, LangChain, ChromaDB, HuggingFace Embeddings, Streamlit\n",
        "```\n\n",
        "---\n\n",
        "## PROJECT COMPLETE!\n\n",
        "You built a complete AI product in 3 days:\n",
        "- Day 96: Core RAG pipeline (document loading, chunking, retrieval)\n",
        "- Day 97: Multi-agent system (Researcher, Writer, Reviewer + LangGraph)\n",
        "- Day 98: Streamlit UI, deployment, portfolio README\n\n",
        "**This is a REAL project you can show in interviews. Ship it to GitHub today!**"
    ]},
]

nb98 = {"cells": cells98, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}}, "nbformat": 4, "nbformat_minor": 4}
with open(os.path.join(day98, "Day98_ResearchAI_UI_Deploy.ipynb"), "w", encoding="utf-8") as f:
    json.dump(nb98, f, indent=1, ensure_ascii=False)
print("Day 98 done!")
print("=== RESEARCHAI CAPSTONE COMPLETE! (Days 96-98) ===")
